/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-01 05:00:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mypackage.model.Message;
import com.mypackage.connection.DbCon;
import com.mypackage.model.User;
import com.mypackage.dao.ProductDao;
import com.mypackage.dao.CartDao;
import com.mypackage.model.User;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/css-js.jsp", Long.valueOf(1713262393428L));
    _jspx_dependants.put("/includes/navbar.jsp", Long.valueOf(1714420048446L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("com.mypackage.dao.CartDao");
    _jspx_imports_classes.add("com.mypackage.model.Message");
    _jspx_imports_classes.add("com.mypackage.connection.DbCon");
    _jspx_imports_classes.add("com.mypackage.dao.ProductDao");
    _jspx_imports_classes.add("com.mypackage.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error_exception.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User activeUser = (User) session.getAttribute("activeUser");
if (activeUser == null) {
	Message message = new Message("You are not logged in! Login first!!", "error", "alert-danger");
	session.setAttribute("message", message);
	response.sendRedirect("login.jsp");
	return;
}
String from = (String) session.getAttribute("from");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Checkout</title>\r\n");
      out.write("<!--CSS-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\" crossorigin=\"anonymous\">\r\n");
      out.write("<!--font awesome-->\r\n");
      out.write("<!--<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/styles.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--JavaScript-->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"JS/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--jQuery-->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!--sweet alert-->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--navbar -->\r\n");
      out.write("	");
      out.write("<link rel=\"stylesheet\" href=\"css/styles.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");


User user=(User) session.getAttribute("activeUser");


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg  bg-purple\" data-bs-theme=\"dark\" style=\"width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("           \r\n");
      out.write("            <a class=\"navbar-brand btn\" href=\"index.jsp\" style=\"transition: outline 5s; text-decoration: none;\" onmouseover=\"this.style.outline='1px solid #17a2b8';\" onmouseout=\"this.style.outline='none';\">\r\n");
      out.write("    <img src=\"about/rlk-2png.png\" style=\"width: 50px; height: 25px; border-radius: 5px; margin-top: 0;\">&nbsp;Rhythm.LK\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <li class=\"nav-item\" style=\"list-style-type: none;\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" aria-current=\"page\" href=\"index.jsp\" style=\"text-decoration: none;\"><i class=\"fas fa-home\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("            <!-- Search bar -->\r\n");
      out.write("            <form class=\"d-flex\" style=\"padding-left: 30px;\">\r\n");
      out.write("                <input class=\"form-control me-2 text-center\" type=\"search\" placeholder=\"What Are You Looking For?\" aria-label=\"Search\" style=\"width: 550px; background-color: white;\">\r\n");
      out.write("                <button class=\"btn btn-outline-light\" type=\"submit\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- End of search bar -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content-end \" id=\"navbarSupportedContent\">\r\n");
      out.write("                <ul class=\"navbar-nav mr-auto mb-2 mb-lg-0 \">\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"cart.jsp\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  \r\n");
      out.write("                    \r\n");
      out.write("                 ");
   if(user==null){ 
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"login.jsp\">Login</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"LogAdmin.jsp\">Admin</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"Register.jsp\">SignUp</a>\r\n");
      out.write("              ");
       }
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    	\r\n");
      out.write("                    	<li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"order.jsp\">Orders</a>\r\n");
      out.write("                          <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"Logout?user=user\">Logout</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                      \r\n");
      out.write("                 \r\n");
      out.write("            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container  mt-5\"\r\n");
      out.write("		style=\"font-size: 17px; text-align: center; margin-left: 250px; margin-right: auto;\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Delivery Address Container -->\r\n");
      out.write("			<div class=\"col-md-8\">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div class=\"container px-3 py-4\">\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"container-fluid text-white\"\r\n");
      out.write("								style=\"background-color: #7e57c2;\">\r\n");
      out.write("								<h4>Delivery Address</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<br>\r\n");
      out.write("						<div class=\"mt-3 mb-3\">\r\n");
      out.write("							<h5>");
      out.print(user.getUserName());
      out.write("\r\n");
      out.write("								&nbsp;\r\n");
      out.write("								");
      out.print(user.getUserPhone());
      out.write("</h5>\r\n");
      out.write("							");

							StringBuilder str = new StringBuilder();
							str.append(user.getUserAddress() + ", ");
							str.append(user.getUserCity() + ", ");
							str.append(user.getUserCity() + ", ");
							str.append(user.getUserPincode());
							out.println(str);
							
      out.write("\r\n");
      out.write("							<br> <br>\r\n");
      out.write("							<div>\r\n");
      out.write("								<div style=\"margin-left: 30px; margin-right: auto;\">\r\n");
      out.write("									<button type=\"button\" class=\"btn btn-outline-info\"\r\n");
      out.write("										data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
      out.write("										Change Address</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<!-- Form -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<form action=\"OrderOperationServlet\" method=\"post\">\r\n");
      out.write("							<div class=\"card\">\r\n");
      out.write("								<div class=\"container-fluid text-white\"\r\n");
      out.write("									style=\"background-color: #7e57c2;\">\r\n");
      out.write("									<h4>Payment Options</h4>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-check form-check-inline\">\r\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"paymentMode\"\r\n");
      out.write("									id=\"creditCard\" value=\"Credit Card\" required> <label\r\n");
      out.write("									class=\"form-check-label\" for=\"creditCard\">Credit</label>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-check form-check-inline\">\r\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"paymentMode\"\r\n");
      out.write("									id=\"debitCard\" value=\"Debit Card\" required> <label\r\n");
      out.write("									class=\"form-check-label\" for=\"debitCard\">Debit</label>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-check form-check-inline\">\r\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"paymentMode\"\r\n");
      out.write("									id=\"atmCard\" value=\"Cash-On-Delivery\" required> <label\r\n");
      out.write("									class=\"form-check-label\" for=\"atmCard\">COD</label>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<input class=\"form-control mt-3\" type=\"number\"\r\n");
      out.write("									placeholder=\"Card Number\" name=\"cardno\">\r\n");
      out.write("								<div class=\"row gx-5\">\r\n");
      out.write("									<div class=\"col mt-3\">\r\n");
      out.write("										<input class=\"form-control\" type=\"number\"\r\n");
      out.write("											placeholder=\"Enter CVV\" name=\"cvv\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col mt-3\">\r\n");
      out.write("										<input class=\"form-control\" type=\"text\" placeholder=\"MM/YY\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<input class=\"form-control mt-3\" type=\"text\"\r\n");
      out.write("									placeholder=\"Card holder name\" name=\"name\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Total Price Details Container -->\r\n");
      out.write("\r\n");
      out.write("							<div>\r\n");
      out.write("								<div class=\"card\">\r\n");
      out.write("									<div class=\"container px-3 py-3\">\r\n");
      out.write("\r\n");
      out.write("										<div class=\"container-fluid text-white\"\r\n");
      out.write("											style=\"background-color: #7e57c2;\">\r\n");
      out.write("											<h4>Price Details</h4>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										");

										if (from.trim().equals("cart")) {
											CartDao cartDao = new CartDao(DbCon.getConnection());
											int totalProduct = cartDao.getCartCountByUserId(user.getUserId());
											float totalPrice = (float) session.getAttribute("totalPrice");
										
      out.write("\r\n");
      out.write("										<table class=\"table table-borderless\">\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>Total Items</td>\r\n");
      out.write("												<td>");
      out.print(totalProduct);
      out.write("</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>Sub Total</td>\r\n");
      out.write("												<td>LKR  ");
      out.print(totalPrice);
      out.write("</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>Shipping Charges</td>\r\n");
      out.write("												<td>LKR  40</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>Logistics Charges</td>\r\n");
      out.write("												<td>LKR  29</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td><h5>Total Price :</h5></td>\r\n");
      out.write("												<td><h5>\r\n");
      out.write("														LKR \r\n");
      out.write("														");
      out.print(totalPrice + 69);
      out.write("</h5></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</table>\r\n");
      out.write("										");

										} else {
										ProductDao productDao = new ProductDao(DbCon.getConnection());
										int pid = (int) session.getAttribute("pid");
										float price = productDao.getProductPriceById(pid);
										
      out.write("\r\n");
      out.write("										<table class=\"table table-borderless\">\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>Total Items</td>\r\n");
      out.write("												<td>1</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>Sub Total</td>\r\n");
      out.write("												<td>LKR ");
      out.print(price);
      out.write("</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>Shipping Charges</td>\r\n");
      out.write("												<td>LKR 40</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>Logistic Charges</td>\r\n");
      out.write("												<td>LKR 29</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td><h5>Total Price :</h5></td>\r\n");
      out.write("												<td><h5>\r\n");
      out.write("														LKR\r\n");
      out.write("														");
      out.print(price + 69);
      out.write("</h5></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</table>\r\n");
      out.write("										");

										}
										
      out.write("\r\n");
      out.write("										<div\r\n");
      out.write("											style=\"font-size: 17px; margin-left: 30px; margin-right: auto;\">\r\n");
      out.write("											<button type=\"submit\"\r\n");
      out.write("												class=\"btn btn-lg btn-outline-success mt-3\">Place\r\n");
      out.write("												Order</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- End of Form -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--Change Address Model -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Change\r\n");
      out.write("						Address</h1>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<form action=\"UpdateUserServlet\" method=\"post\">\r\n");
      out.write("					<input type=\"hidden\" name=\"operation\" value=\"changeAddress\">\r\n");
      out.write("					<div class=\"modal-body mx-3\">\r\n");
      out.write("						<div class=\"mt-2\">\r\n");
      out.write("							<label class=\"form-label fw-bold\">Address</label>\r\n");
      out.write("							<textarea name=\"user_address\" rows=\"3\"\r\n");
      out.write("								placeholder=\"Enter Address(Area and Street))\"\r\n");
      out.write("								class=\"form-control\" required></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-2\">\r\n");
      out.write("							<label class=\"form-label fw-bold\">City</label> <input\r\n");
      out.write("								class=\"form-control\" type=\"text\" name=\"city\"\r\n");
      out.write("								placeholder=\"City/District/Town\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-2\">\r\n");
      out.write("							<label class=\"form-label fw-bold\">Pin Code</label> <input\r\n");
      out.write("								class=\"form-control\" type=\"number\" name=\"pincode\"\r\n");
      out.write("								placeholder=\"Pincode\" maxlength=\"6\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-2\">\r\n");
      out.write("							<label class=\"form-label fw-bold\">State</label> <select\r\n");
      out.write("								name=\"state\" class=\"form-select\">\r\n");
      out.write("								<option selected>--Select State--</option>\r\n");
      out.write("								<option value=\"Western\">Western</option>\r\n");
      out.write("								<option value=\"Southern\">Southern</option>\r\n");
      out.write("								<option value=\"Northern\">Northern</option>\r\n");
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("							data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">Save</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- end model -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
