/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-29 19:47:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.SQLException;
import com.mypackage.connection.DbCon;
import com.mypackage.model.*;
import com.mypackage.dao.ProductDao;
import java.util.List;
import com.mypackage.model.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/includes/css-js.jsp", Long.valueOf(1713262393428L));
    _jspx_dependants.put("/includes/navbar.jsp", Long.valueOf(1714420048446L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1714073195591L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.mypackage.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.mypackage.connection.DbCon");
    _jspx_imports_classes.add("com.mypackage.dao.ProductDao");
    _jspx_imports_classes.add("com.mypackage.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\"/>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write("<!--CSS-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\" crossorigin=\"anonymous\">\r\n");
      out.write("<!--font awesome-->\r\n");
      out.write("<!--<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/styles.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--JavaScript-->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"JS/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--jQuery-->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!--sweet alert-->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Welcome to Ecommerce site</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("@import url(https://fonts.google.com/specimen/Bebas+Neue);\r\n");
      out.write("*\r\n");
      out.write("{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: Bebas Neue;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body.body\r\n");
      out.write("{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: flex-end;\r\n");
      out.write("    align-items: flex-end;\r\n");
      out.write("    min-height: 100vh;\r\n");
      out.write("    background: #333;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer\r\n");
      out.write("{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background: #3586ff;\r\n");
      out.write("    min-height: 100px;\r\n");
      out.write("    padding: 20px 50px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center ;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .social_media,\r\n");
      out.write("footer .menu\r\n");
      out.write("{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .social_media li,\r\n");
      out.write("footer .menu li\r\n");
      out.write("{\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .social_media li a\r\n");
      out.write("{\r\n");
      out.write("    font-size: 2em;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    margin: 0 10px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    transition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .social_media li a:hover\r\n");
      out.write("{\r\n");
      out.write("    transform: translateY(-15px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .menu li a\r\n");
      out.write("{\r\n");
      out.write("    font-size: 1.2em;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    margin: 0 10px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    opacity: 0.75;\r\n");
      out.write("    word-spacing: 30px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .menu li a:hover\r\n");
      out.write("{\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer p\r\n");
      out.write("{\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    font-size: 1.1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .wave\r\n");
      out.write("{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -100px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    background: url(wave.png);\r\n");
      out.write("    background-size: 1000px 100px;\r\n");
      out.write("}\r\n");
      out.write("footer .wave#wave1\r\n");
      out.write("{\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    animation: animateWave 4s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("footer .wave#wave2\r\n");
      out.write("{\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("    opacity: 0.5;\r\n");
      out.write("    bottom: 10px;\r\n");
      out.write("    animation: animateWave_02 4s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("footer .wave#wave3\r\n");
      out.write("{\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    opacity: 0.2;\r\n");
      out.write("    bottom: 15px;\r\n");
      out.write("    animation: animateWave 3s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("footer .wave#wave4\r\n");
      out.write("{\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("    opacity: 0.7;\r\n");
      out.write("    bottom: 20px;\r\n");
      out.write("    animation: animateWave_02 3s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@keyframes animateWave\r\n");
      out.write("{\r\n");
      out.write("    0%\r\n");
      out.write("    {\r\n");
      out.write("        background-position-x: 1000px;\r\n");
      out.write("    }\r\n");
      out.write("    100%\r\n");
      out.write("    {\r\n");
      out.write("        background-position-x: 0px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes animateWave_02\r\n");
      out.write("{\r\n");
      out.write("    0%\r\n");
      out.write("    {\r\n");
      out.write("        background-position-x: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    100%\r\n");
      out.write("    {\r\n");
      out.write("        background-position-x: 1000px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.img{\r\n");
      out.write("\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin: 50px 0;\r\n");
      out.write("    border-radius: 30%;\r\n");
      out.write("    width:50px ;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    bottom: -100px;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    float: left;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel Zooming Effect -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".carousel-item img {\r\n");
      out.write("	transition: transform 3s ease-in-out;\r\n");
      out.write("	transform-origin: center center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".zoom-in {\r\n");
      out.write("	transform: scale(1.2);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            const carousel = document.getElementById('carouselAutoplaying');\r\n");
      out.write("            const imgs = carousel.querySelectorAll('.carousel-item img');\r\n");
      out.write("\r\n");
      out.write("            carousel.addEventListener('slid.bs.carousel', function() {\r\n");
      out.write("                imgs.forEach(function(img) {\r\n");
      out.write("                    img.classList.remove('zoom-in');\r\n");
      out.write("                });\r\n");
      out.write("                const activeCarouselItem = carousel.querySelector('.carousel-item.active');\r\n");
      out.write("                const activeImgs = activeCarouselItem.querySelectorAll('img');\r\n");
      out.write("                activeImgs.forEach(function(img) {\r\n");
      out.write("                    img.classList.add('zoom-in');\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Apply zoom to the first carousel item initially\r\n");
      out.write("            const firstImg = carousel.querySelector('.carousel-item.active img');\r\n");
      out.write("            firstImg.classList.add('zoom-in');\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("<!-- End of Carousel Zooming Effect -->\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel text -->\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".carousel-caption {\r\n");
      out.write("	/* Align caption text to the left */\r\n");
      out.write("	color: white;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 900px; /* Adjust right positioning as needed */\r\n");
      out.write("	bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption h2, .carousel-caption p {\r\n");
      out.write("	color: inherit; /* Inherit color from .carousel-caption */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption-second {\r\n");
      out.write("	/* Align caption text to the right */\r\n");
      out.write("	color: white;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 100px; /* Adjust right positioning as needed */\r\n");
      out.write("	bottom: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption-second h2, .carousel-caption-second p {\r\n");
      out.write("	color: inherit; /* Inherit color from .carousel-caption */\r\n");
      out.write("	font-size: 2rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".popup {\r\n");
      out.write("	display: none;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	transform: translate(-50%, -50%);\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	z-index: 999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup.show {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup-content {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup-title {\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup-message {\r\n");
      out.write("	font-size: 1rem;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup-close-btn {\r\n");
      out.write("	background-color: green;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 8px 16px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: black;\">\r\n");
      out.write("	");
      out.write("<link rel=\"stylesheet\" href=\"css/styles.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");


User user=(User) session.getAttribute("activeUser");


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg  bg-purple\" data-bs-theme=\"dark\" style=\"width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("           \r\n");
      out.write("            <a class=\"navbar-brand btn\" href=\"index.jsp\" style=\"transition: outline 5s; text-decoration: none;\" onmouseover=\"this.style.outline='1px solid #17a2b8';\" onmouseout=\"this.style.outline='none';\">\r\n");
      out.write("    <img src=\"about/rlk-2png.png\" style=\"width: 50px; height: 25px; border-radius: 5px; margin-top: 0;\">&nbsp;Rhythm.LK\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <li class=\"nav-item\" style=\"list-style-type: none;\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" aria-current=\"page\" href=\"index.jsp\" style=\"text-decoration: none;\"><i class=\"fas fa-home\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("            <!-- Search bar -->\r\n");
      out.write("            <form class=\"d-flex\" style=\"padding-left: 30px;\">\r\n");
      out.write("                <input class=\"form-control me-2 text-center\" type=\"search\" placeholder=\"What Are You Looking For?\" aria-label=\"Search\" style=\"width: 550px; background-color: white;\">\r\n");
      out.write("                <button class=\"btn btn-outline-light\" type=\"submit\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- End of search bar -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content-end \" id=\"navbarSupportedContent\">\r\n");
      out.write("                <ul class=\"navbar-nav mr-auto mb-2 mb-lg-0 \">\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"cart.jsp\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  \r\n");
      out.write("                    \r\n");
      out.write("                 ");
   if(user==null){ 
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"login.jsp\">Login</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"LogAdmin.jsp\">Admin</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"Register.jsp\">SignUp</a>\r\n");
      out.write("              ");
       }
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    	\r\n");
      out.write("                    	<li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"order.jsp\">Orders</a>\r\n");
      out.write("                          <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"Logout?user=user\">Logout</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                      \r\n");
      out.write("                 \r\n");
      out.write("            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Carousel -->\r\n");
      out.write("		<div id=\"carouselAutoplaying\"\r\n");
      out.write("			class=\"carousel slide carousel-dark mt-3 mb-3\"\r\n");
      out.write("			data-bs-ride=\"carousel\" data-bs-pause=\"hover=\"false\"\">\r\n");
      out.write("			<div class=\"carousel-inner\">\r\n");
      out.write("				<div class=\"carousel-item active\">\r\n");
      out.write("					<img src=\"product-images\\caroselnew3.jpg\" alt=\"...\" />\r\n");
      out.write("\r\n");
      out.write("					<div class=\"carousel-caption\">\r\n");
      out.write("						<h2 id=\"typed-text-1\" style=\"color: white; font-size: 2rem;\"></h2>\r\n");
      out.write("						<p id=\"typed-text-2\"\r\n");
      out.write("							style=\"color: white; font-family: 'Bebas Neue', cursive;\"></p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"carousel-caption-second\">\r\n");
      out.write("						<h2 style=\"color: white; font-family: 'Bebas Neue', cursive;\">Welcome To Rhythm.LK</h2>\r\n");
      out.write("						<p style=\"color: white; font-size: 1.5rem; font-family: 'Bebas Neue', cursive;\">Shop the Best Gear\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"product-images\\caroselnew.jpg\" alt=\"...\">\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"product-images\\caroselnew2.webp\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"product-images\\carosel4.webp\" alt=\"...\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("				data-bs-target=\"#carouselAutoplaying\" data-bs-slide=\"prev\">\r\n");
      out.write("				<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"\r\n");
      out.write("					style=\"color: black;\"></span> <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("				data-bs-target=\"#carouselAutoplaying\" data-bs-slide=\"next\">\r\n");
      out.write("				<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- end of carousel -->\r\n");
      out.write("\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "products.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Banner-->\r\n");
      out.write("		<div class=\"container-fluid banner-container\" style=\"margin-bottom: 150px;\">\r\n");
      out.write("			<img src=\"product-images\\banner.png\" alt=\"Banner Image\"\r\n");
      out.write("				style=\"width: 100%;\" class=\"img-fluid\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<script src=\"https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js\"></script>\r\n");
      out.write("		<script>\r\n");
      out.write("  // Script for typed animation effect\r\n");
      out.write("\r\n");
      out.write(" const typedText1Element = document.getElementById('typed-text-1');\r\n");
      out.write("  const typedText2Element = document.getElementById('typed-text-2');\r\n");
      out.write("\r\n");
      out.write("  if (typedText1Element) {\r\n");
      out.write("    const typed1 = new Typed('#typed-text-1', {\r\n");
      out.write("      strings: [\"Now Available....\"],\r\n");
      out.write("      typeSpeed: 30, \r\n");
      out.write("      backSpeed: 0, \r\n");
      out.write("    });\r\n");
      out.write("  } else {\r\n");
      out.write("    console.error('Element with ID \"typed-text-1\" not found.');\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  if (typedText2Element) {\r\n");
      out.write("    const typed2 = new Typed('#typed-text-2', {\r\n");
      out.write("      strings: [\"Fender American Vintage II Stratocaster Series.....\"],\r\n");
      out.write("      typeSpeed: 30,\r\n");
      out.write("      backSpeed: 0,\r\n");
      out.write("    });\r\n");
      out.write("  } else {\r\n");
      out.write("    console.error('Element with ID \"typed-text-2\" not found.');\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // Repeat similar code for other carousel captions you want to animate\r\n");
      out.write("  // (replace IDs with corresponding IDs from your HTML)\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("		");

		String order = (String) session.getAttribute("order");
		if (order != null) {
		
      out.write("\r\n");
      out.write("		<div id=\"order-confirmation-popup\" class=\"popup\">\r\n");
      out.write("			<div class=\"popup-content\">\r\n");
      out.write("				<i class=\"fas fa-check-circle\"\r\n");
      out.write("					style=\"color: green; font-size: 2rem; margin-right: 10px;\"></i>\r\n");
      out.write("				<h2 class=\"popup-title\">Order Placed, Thank you!</h2>\r\n");
      out.write("				<p class=\"popup-message\">Your Order is Processing Now</p>\r\n");
      out.write("				<button class=\"popup-close-btn\">Close</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script>\r\n");
      out.write("  const popup = document.getElementById(\"order-confirmation-popup\");\r\n");
      out.write("  if (popup) {\r\n");
      out.write("    setTimeout(() => {\r\n");
      out.write("      popup.classList.add(\"show\"); // Show popup after a delay\r\n");
      out.write("    }, 100); // Adjust delay as needed\r\n");
      out.write("    \r\n");
      out.write("    const closeBtn = document.querySelector(\".popup-close-btn\");\r\n");
      out.write("    closeBtn.addEventListener(\"click\", () => {\r\n");
      out.write("      popup.classList.remove(\"show\");\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    setTimeout(() => {\r\n");
      out.write("        popup.classList.remove(\"show\");\r\n");
      out.write("      }, 5000);\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("		");

		}
		session.removeAttribute("order");
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("<footer>\r\n");
      out.write("        <div class=\"waves\">\r\n");
      out.write("            <div class=\"wave\" id=\"wave1\"></div>\r\n");
      out.write("            <div class=\"wave\" id=\"wave2\"></div>\r\n");
      out.write("            <div class=\"wave\" id=\"wave3\"></div>\r\n");
      out.write("            <div class=\"wave\" id=\"wave4\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"social_media\">\r\n");
      out.write("            <li> <a href=\"#\"> <ion-icon name=\"logo-facebook\"></ion-icon>\r\n");
      out.write("            </a> </li>\r\n");
      out.write("            <li> <a href=\"#\"> <ion-icon name=\"logo-instagram\"></ion-icon></a> </li> \r\n");
      out.write("            <li> <a href=\"#\"> <ion-icon name=\"logo-whatsapp\"></ion-icon>\r\n");
      out.write("            </a> </li>\r\n");
      out.write("            <li> <a href=\"#\"> <ion-icon name=\"logo-linkedin\"></ion-icon>\r\n");
      out.write("            </a> </li>\r\n");
      out.write("            <li> <a href=\"#\"> <ion-icon name=\"logo-twitter\"></ion-icon></a> </li>&emsp;\r\n");
      out.write("            &emsp;&emsp; \r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu\">\r\n");
      out.write("            <li><a href=\"index.jsp\">Home&thinsp;</a></li>\r\n");
      out.write("            <li><a href=\"about/About.html\">&thinsp;&thinsp;&thinsp;About</a></li>\r\n");
      out.write("            <li><a href=\"about/About.html\">Services</a></li>\r\n");
      out.write("            <li><img src=\"about/rlk-2png.png\" style=\"width: 50px; height: 50px;\"> </li>\r\n");
      out.write("            <li><a href=\"about/About.html\">Contact</a></li>\r\n");
      out.write("            <li><a href=\"about/About.html\">Brands</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p> &reg; 2024  Rythem   Musics   |  &copy; All   Right   Reserved </p>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script type=\"module\" src=\"https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("    <script nomodule src=\"https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js\"></script>\"\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
