/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-01 07:50:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mypackage.model.Message;
import com.mypackage.model.User;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/navbar.jsp", Long.valueOf(1714420048446L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1714073195591L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.mypackage.model.Message");
    _jspx_imports_classes.add("com.mypackage.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Registration</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\"/>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("label {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--navbar -->\r\n");
      out.write("	");
      out.write("<link rel=\"stylesheet\" href=\"css/styles.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");


User user=(User) session.getAttribute("activeUser");


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg  bg-purple\" data-bs-theme=\"dark\" style=\"width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("           \r\n");
      out.write("            <a class=\"navbar-brand btn\" href=\"index.jsp\" style=\"transition: outline 5s; text-decoration: none;\" onmouseover=\"this.style.outline='1px solid #17a2b8';\" onmouseout=\"this.style.outline='none';\">\r\n");
      out.write("    <img src=\"about/rlk-2png.png\" style=\"width: 50px; height: 25px; border-radius: 5px; margin-top: 0;\">&nbsp;Rhythm.LK\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <li class=\"nav-item\" style=\"list-style-type: none;\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" aria-current=\"page\" href=\"index.jsp\" style=\"text-decoration: none;\"><i class=\"fas fa-home\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("            <!-- Search bar -->\r\n");
      out.write("            <form class=\"d-flex\" style=\"padding-left: 30px;\">\r\n");
      out.write("                <input class=\"form-control me-2 text-center\" type=\"search\" placeholder=\"What Are You Looking For?\" aria-label=\"Search\" style=\"width: 550px; background-color: white;\">\r\n");
      out.write("                <button class=\"btn btn-outline-light\" type=\"submit\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- End of search bar -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content-end \" id=\"navbarSupportedContent\">\r\n");
      out.write("                <ul class=\"navbar-nav mr-auto mb-2 mb-lg-0 \">\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"cart.jsp\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  \r\n");
      out.write("                    \r\n");
      out.write("                 ");
   if(user==null){ 
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"login.jsp\">Login</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"LogAdmin.jsp\">Admin</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"Register.jsp\">SignUp</a>\r\n");
      out.write("              ");
       }
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    	\r\n");
      out.write("                    	<li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"order.jsp\">Orders</a>\r\n");
      out.write("                          <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link btn btn-outline-info\" href=\"Logout?user=user\">Logout</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                      \r\n");
      out.write("                 \r\n");
      out.write("            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid mt-4\">\r\n");
      out.write("		<div class=\"row g-0\">\r\n");
      out.write("			<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div class=\"card-body px-5\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"container text-center\">\r\n");
      out.write("							<img src=\"Add-Images/newsignup.png\" style=\"max-width: 80px;\"\r\n");
      out.write("								class=\"img-fluid\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<h3 class=\"text-center\">Create Account</h3>\r\n");
      out.write("						\r\n");
      out.write("\r\n");
      out.write("						<!--registration-form-->\r\n");
      out.write("						<form id=\"register-form\" action=\"RegisterServlet\" method=\"post\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-6 mt-2\">\r\n");
      out.write("									<label class=\"form-label\">Your name</label> <input type=\"text\"\r\n");
      out.write("										name=\"user_name\" class=\"form-control\"\r\n");
      out.write("										placeholder=\"First and last name\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 mt-2\">\r\n");
      out.write("									<label class=\"form-label\">Email</label> <input type=\"email\"\r\n");
      out.write("										name=\"user_email\" placeholder=\"Email address\"\r\n");
      out.write("										class=\"form-control\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-6 mt-2\">\r\n");
      out.write("									<label class=\"form-label\">Mobile number</label> <input\r\n");
      out.write("										type=\"number\" name=\"user_mobile_no\"\r\n");
      out.write("										placeholder=\"Mobile number\" class=\"form-control\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 mt-5\">\r\n");
      out.write("									<label class=\"form-label pe-3\">Gender</label> <input\r\n");
      out.write("										class=\"form-check-input\" type=\"radio\" name=\"gender\"\r\n");
      out.write("										value=\"Male\"> <span class=\"form-check-label pe-3 ps-1\">\r\n");
      out.write("										Male </span> <input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("										name=\"gender\" value=\"Female\"> <span\r\n");
      out.write("										class=\"form-check-label ps-1\"> Female </span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mt-2\">\r\n");
      out.write("								<label class=\"form-label\">Address</label> <input type=\"text\"\r\n");
      out.write("									name=\"user_address\"\r\n");
      out.write("									placeholder=\"Enter Address(Area and Street))\"\r\n");
      out.write("									class=\"form-control\" required>\r\n");
      out.write("							</div>  \r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-6 mt-2\">\r\n");
      out.write("									<label class=\"form-label\">City</label> <input\r\n");
      out.write("										class=\"form-control\" type=\"text\" name=\"city\"\r\n");
      out.write("										placeholder=\"City/District/Town\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 mt-2\">\r\n");
      out.write("									<label class=\"form-label\">Pincode</label> <input\r\n");
      out.write("										class=\"form-control\" type=\"number\" name=\"pincode\"\r\n");
      out.write("										placeholder=\"Pincode\" maxlength=\"6\" required>\r\n");
      out.write("								</div>  \r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-6 mt-2\">\r\n");
      out.write("									<label class=\"form-label\">State</label> <select name=\"state\"\r\n");
      out.write("										class=\"form-select\">\r\n");
      out.write("										\r\n");
      out.write("										<option value=\"Western\">Western</option>\r\n");
      out.write("										<option value=\"Southern\">Southern</option>\r\n");
      out.write("										<option value=\"Northern\">Northern</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-md-6 mt-2\">\r\n");
      out.write("									<label class=\"form-label\">Password</label> <input\r\n");
      out.write("										type=\"password\" name=\"user_password\"\r\n");
      out.write("										placeholder=\"Enter Password\" class=\"form-control\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div id=\"submit-btn\" class=\"container text-center mt-4\">\r\n");
      out.write("								<button type=\"submit\" class=\"btn btn-outline-primary me-3\">Submit</button>\r\n");
      out.write("								<button type=\"reset\" class=\"btn btn-outline-primary\">Reset</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"mt-3 text-center\">\r\n");
      out.write("								<h6>\r\n");
      out.write("									Already have an account?<a href=\"login.jsp\"\r\n");
      out.write("										style=\"text-decoration: none\"> Sign in</a>\r\n");
      out.write("								</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
